language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
    - composer self-update
    - composer self-update # to use a stable version
    - composer install --no-scripts

script:
  - bin/phpunit