language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 5.6
  - 7.0
  - 7.1

env:
    matrix:
      - PREFER_LOWEST="--prefer-lowest"
      - PREFER_LOWEST=""

before_script:
    - composer self-update
    - composer update $PREFER_LOWEST

script:
  - vendor/bin/phpunit