parameters:
  security_type: 'db' # db, demo, ldap
  security_ldap_url: 'ldap.forumsys.com'
  security_ldap_dn_string: 'cn=read-only-admin,dc=example,dc=com' # {username}

  public_path: '/'

  notification_email_sender: info@example.com

  dev_delivery_address: ~
  dev_disable_delivery: true