parameters:
  security_type: 'db' # db, demo, ntlm, ldap
  security_ldap_url: 'ldap.forumsys.com'
  security_ldap_dn_string: 'cn=read-only-admin,dc=example,dc=com' # {username}
  security_ntlm_domain: 'workspace'

  public_path: '/'

  notification_email_sender: ~