parameters:
    database_host:       localhost
    database_port:       ~
    database_name:       talkly
    database_user:       talkly
    database_password:

    secret:              secure

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~
