app:
    resource: "@TobiasOlryTalklyBundle/Controller/"
    type:     annotation
    prefix: /api

login:
    path: /api/login

catch_all:
    path:     /{catchall}
    defaults:
        _controller: TobiasOlryTalklyBundle:Index:index
    requirements:
        #catchall: "^(?!api|_)"
        catchall: ".*"

topic:
    path: /topic/{id}