app:
    resource: "@TobiasOlryTalklyBundle/Controller/"
    type:     annotation
    prefix: /api

login:
    path: /api/login

catch_all:
    path:     /{catchall}
    defaults:
        _controller: TobiasOlryTalklyBundle:Index:dashboard
    requirements:
        #catchall: "^(?!api|_)"
        catchall: ".*"