security:
    encoders:
        TobiasOlry\TalklyBundle\Entity\User: bcrypt

    providers:
        talky_user_provider:
            id: talkly.security.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            pattern:   ^/$
            security: false

        api:
            pattern:   ^/
            stateless: true
            lexik_jwt: ~
            guard:
                authenticators:
                    - talkly.security.authenticator