security:
    encoders:
        TobiasOlry\TalklyBundle\Entity\User: plain

    providers:
        talky_user_provider:
            id: talkly.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            security: false

        default:
            pattern: ^/
            logout:
                path:   logout
                target: login
            guard:
                authenticators:
                    - talkly.security.ntlm_authenticator
            form_login_ldap:
                service: talkly.security.authentication.ldap
                dn_string: "%ldap_dn_string%"
                login_path: login
                check_path: login_check