security:
    encoders:
        TobiasOlry\TalklyBundle\Entity\User: bcrypt

    providers:
        talky_user_provider:
            id: talkly.security.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            pattern:   ^/$
            security: false
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true

            ntlm: "%ntlm%"
            form_login_ldap:
                service: talkly.security.authentication.ldap
                dn_string: "%ldap_dn_string%"
                login_path: login
                check_path: login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/
            stateless: true
            lexik_jwt: ~
            guard:
                authenticators:
                    - talkly.security.authenticator